#!/usr/bin/env python3
"""Exploratory offline ML for RegimeEngineV2 hit8-before-minus5.

This script is intentionally not imported by runtime code and does not write any
live configuration. It expects a CSV generated by export_regime_engine_v2_ml_dataset.ts.
"""

from __future__ import annotations

import argparse
import csv
import math
from datetime import datetime, timezone
from pathlib import Path


TARGET = "target_hit8_before_minus5"
DROP_PREFIXES = ("target_",)
CATEGORICAL = {
    "symbol",
    "side",
    "technicalRegime",
    "momentumEnvironment",
    "technicalDirection",
    "transitionRisk",
    "marketConfirmationState",
    "patternKind",
    "patternBreakout",
    "btcAction",
    "ethAction",
    "source",
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Train exploratory RegimeEngineV2 ML model for hit8-before-minus5")
    parser.add_argument("--dataset", help="CSV dataset exported by export:regime-engine-v2-ml-dataset")
    parser.add_argument("--output-dir", default="/home/jasan/Develop")
    parser.add_argument("--test-fraction", type=float, default=0.25)
    args = parser.parse_args()
    if not args.dataset:
        parser.print_help()
        return

    try:
        import numpy as np
        from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
        from sklearn.linear_model import LogisticRegression
        from sklearn.metrics import average_precision_score, roc_auc_score
        from sklearn.preprocessing import OneHotEncoder, StandardScaler
        from sklearn.compose import ColumnTransformer
        from sklearn.pipeline import Pipeline
    except Exception as exc:  # pragma: no cover - environment dependent
        write_missing_dependency_report(args.output_dir, exc)
        return

    rows = read_rows(args.dataset)
    if len(rows) < 100:
        raise SystemExit(f"Dataset too small: {len(rows)} rows")
    rows.sort(key=lambda row: row.get("timestamp", ""))
    split = max(1, min(len(rows) - 1, int(len(rows) * (1 - args.test_fraction))))
    train, test = rows[:split], rows[split:]
    feature_cols = [key for key in rows[0].keys() if key != TARGET and not key.startswith(DROP_PREFIXES)]
    numeric_cols = [key for key in feature_cols if key not in CATEGORICAL and key != "timestamp"]
    categorical_cols = [key for key in feature_cols if key in CATEGORICAL]

    x_train = [[row.get(col, "") for col in feature_cols] for row in train]
    x_test = [[row.get(col, "") for col in feature_cols] for row in test]
    y_train = np.array([int(float(row[TARGET] or 0)) for row in train])
    y_test = np.array([int(float(row[TARGET] or 0)) for row in test])
    feature_index = {col: i for i, col in enumerate(feature_cols)}

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", StandardScaler(), [feature_index[col] for col in numeric_cols]),
            ("cat", OneHotEncoder(handle_unknown="ignore"), [feature_index[col] for col in categorical_cols]),
        ],
        remainder="drop",
    )
    models = {
        "logistic_global": LogisticRegression(max_iter=500, class_weight="balanced"),
        "random_forest_global": RandomForestClassifier(n_estimators=120, min_samples_leaf=20, random_state=7, class_weight="balanced"),
        "hist_gradient_global": HistGradientBoostingClassifier(max_iter=120, learning_rate=0.06, random_state=7),
    }
    results = []
    predictions = []
    importances = []
    for name, model in models.items():
        pipe = Pipeline([("prep", preprocessor), ("model", model)])
        pipe.fit(x_train, y_train)
        proba = pipe.predict_proba(x_test)[:, 1]
        results.append(metrics_for(name, y_test, proba, test))
        predictions.extend(prediction_rows(name, proba, test))
        importances.extend(feature_importance_rows(name, pipe, numeric_cols, categorical_cols))

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    report_path = out_dir / f"aegis_regime_engine_v2_ml_exploratory_{stamp}.md"
    pred_path = out_dir / f"aegis_regime_engine_v2_ml_predictions_{stamp}.csv"
    imp_path = out_dir / f"aegis_regime_engine_v2_ml_feature_importance_{stamp}.csv"
    report_path.write_text(render_report(results, len(train), len(test)), encoding="utf-8")
    write_csv(pred_path, predictions)
    write_csv(imp_path, importances)
    print(f"ML reports written: {report_path}, {pred_path}, {imp_path}")


def read_rows(path: str) -> list[dict[str, str]]:
    with open(path, newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def metrics_for(name, y_true, proba, rows):
    from sklearn.metrics import average_precision_score, roc_auc_score

    roc = safe_metric(lambda: roc_auc_score(y_true, proba))
    pr = safe_metric(lambda: average_precision_score(y_true, proba))
    cutoff = sorted(proba, reverse=True)[max(0, math.ceil(len(proba) * 0.10) - 1)]
    top = [(p, row) for p, row in zip(proba, rows) if p >= cutoff]
    top_hit = sum(int(float(row[TARGET] or 0)) for _, row in top) / max(1, len(top))
    top_mfe = avg(float(row.get("target_mfe_roe_60m") or 0) for _, row in top)
    top_mae = avg(abs(float(row.get("target_mae_roe_60m") or 0)) for _, row in top)
    precision_top = top_hit
    return {
        "model": name,
        "roc_auc": roc,
        "pr_auc": pr,
        "precision_top10": precision_top,
        "top_decile_hit8": top_hit,
        "top_decile_mfe_mae": top_mfe / top_mae if top_mae else None,
    }


def prediction_rows(model, proba, rows):
    return [
        {
            "model": model,
            "timestamp": row.get("timestamp", ""),
            "symbol": row.get("symbol", ""),
            "side": row.get("side", ""),
            "prob_hit8": p,
            "target_hit8_before_minus5": row.get(TARGET, ""),
        }
        for p, row in zip(proba, rows)
    ]


def feature_importance_rows(model_name, pipe, numeric_cols, categorical_cols):
    model = pipe.named_steps["model"]
    if not hasattr(model, "feature_importances_"):
        return []
    encoder = pipe.named_steps["prep"].named_transformers_["cat"]
    names = list(numeric_cols) + list(encoder.get_feature_names_out(categorical_cols))
    return [
        {"model": model_name, "feature": name, "importance": importance}
        for name, importance in sorted(zip(names, model.feature_importances_), key=lambda item: item[1], reverse=True)[:80]
    ]


def render_report(results, train_count, test_count):
    lines = [
        "# RegimeEngineV2 ML Exploratory",
        "",
        f"Train rows: {train_count}",
        f"Test rows: {test_count}",
        "",
        "| model | ROC AUC | PR AUC | precision@top10% | top decile hit8 | top decile MFE/MAE |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for row in results:
        lines.append(
            f"| {row['model']} | {fmt(row['roc_auc'])} | {fmt(row['pr_auc'])} | {fmt(row['precision_top10'])} | {fmt(row['top_decile_hit8'])} | {fmt(row['top_decile_mfe_mae'])} |"
        )
    lines.extend([
        "",
        "This is exploratory only. Do not connect to live trading without out-of-sample walk-forward validation and calibration review.",
    ])
    return "\n".join(lines) + "\n"


def write_missing_dependency_report(output_dir: str, exc: Exception) -> None:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    path = Path(output_dir) / f"aegis_regime_engine_v2_ml_exploratory_{stamp}.md"
    path.write_text(f"# RegimeEngineV2 ML Exploratory\n\nSkipped: sklearn/numpy unavailable: {exc}\n", encoding="utf-8")
    print(f"ML skipped, dependency report written: {path}")


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def safe_metric(fn):
    try:
        return fn()
    except Exception:
        return None


def avg(values):
    values = list(values)
    return sum(values) / len(values) if values else 0


def fmt(value):
    return "n/a" if value is None else f"{value:.6f}"


if __name__ == "__main__":
    main()
